### ISSUE TITLE
ontology.ttl buggies

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/DataId-Ontology#8]
- vann:preferredNamespaceUri should be string not URL
- use all defined prefixes to the max. Eg the opening should become

```
dataid: a owl:Ontology ;
    vann:preferredNamespaceUri "http://dataid.dbpedia.org/ns/core#" ;
    vann:preferredNamespacePrefix "dataid"^^xsd:string ;
    owl:versionInfo "1.0.0" ; 
    rdfs:comment "DBpedia Data ID is an ontology with the goal of extensively describing datasets via RDF files in a uniform way. Established vocabularies like DCAT, VoID, Prov-O are used for maximum compatibility."@en ;
    rdfs:label "DataID"@en ;
    owl:imports void: , dcat: , prov: .
```
- remove this recursive thing

```
dataid: rdfs:isDefinedBy dataid: ;
```
- why this roundabout way for "refining dcat:Catalog to fit DCAT-AP profile"?

```
[]  a owl:Class;
    owl:equivalentClass dcat:Catalog; ...
```
- better this `dcat:Catalog ...` which is no more hijacking than the roundabout way
- typo `dataid:softwareRquirement`
- review comments, eg `version of a DataIdPart` thrice but there's no `DataIdPart`

Finally: shoudln't `dataid-ld:SparqlEndpoint` be subclass of `dataid:ServiceEndpoint` ?

**Comment by chile12** [comment]
Thank you Vladimir for your input.

DataID has changed a bit since this Issue was raised. 
Most important is the separation of Ontology and (most) restrictions with use of SHACL.
Which, in the end, will produce a OWL 2 RL compatible ontology.
Also, the fleeting idea of following DCAT-AP has been dropped (and also has not been adopted with SHACLE), since DCAT-AP has some profound issues regarding its adherence to DCAT principles itself (e.g. making dcat:accessURL mandatory), and i find the decision of accepting/endorsing it by the ISA Committee as  premature.

All other changes proposed have been adopted, thank you.
